service: serverless-telegram-bot

useDotenv: true

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: ap-northeast-2
  environment:
    TELEGRAM_TOKEN: ${env:TOKEN}

functions:
  post:
    handler: serverless.handler
    events:
      - http:
          path: my-custom-url
          method: post
          cors: true