service: serverless-telegram-bot

useDotenv: true

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: ap-northeast-2
  environment:
    TOKEN: ${env:TOKEN}
    PROJECT_ID: ${env:PROJECT_ID}
    STAKE_ADDRESS: ${env:STAKE_ADDRESS}
    DONATION_ADDRESS: ${env:DONATION_ADDRESS}

functions:
  post:
    handler: index.handler
    events:
      - http:
          path: my-custom-url
          method: post
          cors: true